package filecollate

import (
	"errors"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"syscall"

	"github.com/puzpuzpuz/xsync/v3"
	"golang.org/x/sync/errgroup"
)

type pair struct {
	key  string // depends on the KeyGeneratorFunc
	path string
}

type filecollate struct {
	g           *errgroup.Group  // "wait group" to limit the num of concurrent search workers
	pairs       chan *pair       // channel to send pairs to, which are processed and sent to the caller
	shutdown    chan os.Signal   // channel to receive shutdown signals on
	generatorFn KeyGeneratorFunc // function that generates a key for a given path to identify files to group
	filters     Filters          // filters to apply when searching for files to group
}

func newFilecollate(c Cfg) *filecollate {
	g := new(errgroup.Group)
	g.SetLimit(c.Workers)

	return &filecollate{
		g:           g,
		pairs:       make(chan *pair, c.Workers),
		shutdown:    make(chan os.Signal, 1),
		generatorFn: c.KeyGenerator,
		filters:     c.Filters,
	}
}

// Starts the search for files to group which can be customized by the provided Cfg struct.
func run(c Cfg, collectorChan chan []string, stream bool) error {
	c.defaults()
	fc := newFilecollate(c)

	go fc.consumePairs(collectorChan, stream)
	go gracefulShutdown(fc.shutdown)

	for _, path := range c.Paths {
		p := path
		fc.g.Go(func() error {
			return fc.search(p)
		})
	}

	err := fc.g.Wait()
	close(fc.pairs) // Trigger pair consumer to process the results.
	return err
}

// Runs the search and returns a flat slice of all grouped paths.
func GetResults(c Cfg) ([]string, error) {
	collectorChan := make(chan []string, 1)
	err := run(c, collectorChan, false)
	return <-collectorChan, err
}

// Runs the search and streams the grouped paths to the provided channel
// as they are found.
func StreamResults(c Cfg, collectorChan chan []string) error {
	return run(c, collectorChan, true)
}

// Processes the produced pairs and sends the results to the provided channel.
// Depending on the stream bool, results are either sent in chunks or all at once.
func (fc *filecollate) consumePairs(collectorChan chan []string, stream bool) {
	defer close(collectorChan)

	// key -> last encountered path
	m := xsync.NewMapOf[string, string]()

	for p := range fc.pairs {
		storedPath, ok := m.Load(p.key)
		if !ok {
			m.Store(p.key, p.path)
			continue
		}
		// When storedPath is not empty, it indicates that we have found the first match,
		// so we send both the stored path and the current path.
		if storedPath != "" {
			m.Store(p.key, "")
			paths := []string{storedPath, p.path}
			if stream {
				// Send in chunks.
				collectorChan <- paths
				continue
			}
			// Not streaming, collect all paths.
			select {
			case currfces := <-collectorChan:
				collectorChan <- append(currfces, paths...)
			default:
				collectorChan <- paths
			}
			continue
		}
		// Previous grouped paths have already been sent, so just send the current path.
		if stream {
			collectorChan <- []string{p.path}
			continue
		}
		// Select is not needed since at this point the collectorChan can't be empty or full.
		collectorChan <- append(<-collectorChan, p.path)
	}
}

// Produces a pair with the key which is generated by `fc.generatorFn` and the path
// which is then sent to the pairs channel.
func (fc *filecollate) producePair(path string) error {
	if fc.shuttingDown() {
		return nil // Stop pair production if shutdown is in progress.
	}

	key, err := fc.generatorFn(path)
	if err != nil {
		if errors.Is(err, ErrSkipFile) {
			return nil // Don't collect ErrSkipFile errors
		}
		return err
	}

	if key == "" {
		return fmt.Errorf("\nkey generator returned an empty key for path: %s", path)
	}

	fc.pairs <- &pair{key, path}
	return nil
}

// Walks the tree of the provided dir and triggers the production of pairs for each valid file.
func (fc *filecollate) search(dir string) error {
	return filepath.WalkDir(dir, func(path string, de os.DirEntry, err error) error {
		if fc.shuttingDown() {
			return nil
		}

		if err != nil {
			return err
		}

		if de.IsDir() && fc.filters.skipDir(path) {
			return filepath.SkipDir
		}

		if de.Type().IsRegular() && !fc.filters.skipFile(path) {
			fi, err := de.Info()
			if err != nil || fi.Size() == 0 {
				return nil
			}

			fc.g.Go(func() error {
				return fc.producePair(path)
			})
		}

		return nil
	})
}

// Helper to check if a shutdown signal has been received.
func (fc *filecollate) shuttingDown() bool {
	select {
	case <-fc.shutdown:
		return true
	default:
		return false
	}
}

// Sets up a signal handler worker for graceful shutdown.
func gracefulShutdown(shutdown chan os.Signal) {
	signal.Notify(shutdown, syscall.SIGINT, syscall.SIGTERM)
	<-shutdown
	log.Println("\nReceived signal, shutting down after current workers are done...")
	close(shutdown)
}
